version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/jordanrblum
    docker:
      - image: samueldebruyn/debian-git
    steps:
      - checkout
      - run:
          name: Deploy 
          command: |
              apt-get update
              apt-get -qq install git-ftp
              echo "'_$(git status -uno --porcelain | wc -l)_'"
              git status -uno --porcelain
              echo "Initiating Push site: jordanrblum.com."
              git ftp init --user "process.env.FTPUSERNAME" --passwd "process.env.FTPPASS" process.env.FTPHOST

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
