version: 2
jobs:
   build:
     docker:
       - image: samueldebruyn/debiat-git
      steps:
        - checkout
        - deploy:
            name: Deploy to host if branch is master
            command: |
              apt-get update
              apt-get -qq install git-ftp
              echo "'_$(git status -uno --porcelain | wc -l)_'"
              git status -uno --porcelain
              echo "Initiating Push site:labs.kosmik.id."
              git ftp init --user "process.env.FTPUSERNAME" --passwd "process.env.FTPPASS" process.env.FTPHOST

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
