version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/jordanrblum
    docker:
      - image: samueldebruyn/debian-git
    steps:
      - checkout
      - run:
          name: Deploy 
          command: |
              apt-get update
              apt-get -qq install git-ftp
              echo "'_$(git status -uno --porcelain | wc -l)_'"
              git status -uno --porcelain
              echo "Initiating Push site: jordanrblum.com."
              pwd
              git config git-ftp.url ftp://$FTPHOST
              git config git-ftp.user $FTPUSERNAME
              git config git-ftp.password $FTPPASS
              git ftp push

# Orchestrate our job run sequence
workflows:
  deploy-to-server:
    jobs:
      - build
